"""Generate src/policy_net.h from a NARCPOL2 binary policy."""

from pathlib import Path
import sys

source = Path(sys.argv[1] if len(sys.argv) > 1 else "networks/narc-next-context-policy.bin")
destination = Path(sys.argv[2] if len(sys.argv) > 2 else "src/policy_net.h")
data = source.read_bytes() if source.exists() else b""

with destination.open("w", encoding="utf-8", newline="\n") as stream:
    stream.write("// Generated by tests/embed_policy.py. Do not edit.\n")
    stream.write("#pragma once\n#include <cstddef>\n\n")
    stream.write(f"inline constexpr size_t EMBEDDED_POLICY_SIZE = {len(data)};\n")
    if data:
        stream.write("alignas(64) inline const unsigned char EMBEDDED_POLICY[] = {\n")
        for offset in range(0, len(data), 24):
            values = ",".join(str(value) for value in data[offset : offset + 24])
            stream.write(f"  {values},\n")
        stream.write("};\n")
    else:
        stream.write("alignas(64) inline const unsigned char EMBEDDED_POLICY[] = {0};\n")

print(f"Embedded {len(data)} policy bytes from {source} -> {destination}")
