"""Generate src/nnue_net.h from a NARCNET1 network file."""

from pathlib import Path
import sys

source = Path(sys.argv[1] if len(sys.argv) > 1 else "networks/narc-next.nnue")
destination = Path(sys.argv[2] if len(sys.argv) > 2 else "src/nnue_net.h")
data = source.read_bytes() if source.exists() else b""

with destination.open("w", encoding="utf-8", newline="\n") as stream:
    stream.write("// Generated by tests/embed_net.py. Do not edit.\n")
    stream.write("#pragma once\n#include <cstddef>\n\n")
    stream.write(f"inline constexpr size_t EMBEDDED_NET_SIZE = {len(data)};\n")
    if data:
        stream.write("inline const unsigned char EMBEDDED_NET[] = {\n")
        for offset in range(0, len(data), 24):
            values = ",".join(str(value) for value in data[offset : offset + 24])
            stream.write(f"  {values},\n")
        stream.write("};\n")
    else:
        stream.write("inline const unsigned char EMBEDDED_NET[] = {0};\n")

print(f"Embedded {len(data)} bytes from {source} -> {destination}")
